//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate_in_Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate_in_Event()
        {
            this.Candidate_in_Event_History = new HashSet<Candidate_in_Event_History>();
        }
    
        public int id { get; set; }
        public int Event_id { get; set; }
        public int Candidate_id { get; set; }
        public Nullable<int> GST_FollowUp { get; set; }
        public Nullable<double> FinalGrade { get; set; }
        public Nullable<int> CompletionLevel { get; set; }
        public string Note { get; set; }
        public Nullable<int> CandidateStatus { get; set; }
        public Nullable<int> ContractType { get; set; }
        public string Certificate_id { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Event Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_in_Event_History> Candidate_in_Event_History { get; set; }
    }
}
