//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateHistory
    {
        public int id { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int Candidate_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
