//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Candidate_in_Event = new HashSet<Candidate_in_Event>();
            this.CandidateHistories = new HashSet<CandidateHistory>();
        }
    
        public int id { get; set; }
        public string Account { get; set; }
        public Nullable<int> National_id { get; set; }
        public string CandidateName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Facebook { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public int WorkingTimeAvaiable { get; set; }
        public string Skill { get; set; }
        public Nullable<double> GPA { get; set; }
        public int Faculty_of_University_id { get; set; }
    
        public virtual Faculty_of_University Faculty_of_University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_in_Event> Candidate_in_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateHistory> CandidateHistories { get; set; }
    }
}
