//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECMDBEntities : DbContext
    {
        public ECMDBEntities()
            : base("name=ECMDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Authority> Authorities { get; set; }
        public virtual DbSet<CampuslinkProgram> CampuslinkPrograms { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Candidate_in_Event> Candidate_in_Event { get; set; }
        public virtual DbSet<Candidate_in_Event_History> Candidate_in_Event_History { get; set; }
        public virtual DbSet<CandidateHistory> CandidateHistories { get; set; }
        public virtual DbSet<EventHistory> EventHistories { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Faculty_of_University> Faculty_of_University { get; set; }
        public virtual DbSet<Sub_Subject_Type> Sub_Subject_Type { get; set; }
        public virtual DbSet<University> Universities { get; set; }
    }
}
