//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Candidate_in_Event = new HashSet<Candidate_in_Event>();
            this.EventHistories = new HashSet<EventHistory>();
        }
    
        public int id { get; set; }
		[Required(ErrorMessage ="không được để trống")]
		public string CourseCode { get; set; }
        public int ProgramCode_id { get; set; }
        public string SubjectType { get; set; }
        public int SST_id { get; set; }
        public string FormatType { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public Nullable<double> PlanedExpense { get; set; }
        public string BudgetCode { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<double> ActualExpense { get; set; }
        public string TrainingFeedBack { get; set; }
        public string TrainingFeedBackContent { get; set; }
        public string TrainingFeedBackOrganization { get; set; }
        public Nullable<int> EventStatus { get; set; }
        public Nullable<int> Faculty_of_University_id { get; set; }
        public string Note { get; set; }
		[Required(ErrorMessage ="không được để trống phần này")]
		public string Site { get; set; }
        public Nullable<int> CountDay { get; set; }
    
        public virtual CampuslinkProgram CampuslinkProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate_in_Event> Candidate_in_Event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventHistory> EventHistories { get; set; }
        public virtual Faculty_of_University Faculty_of_University { get; set; }
        public virtual Sub_Subject_Type Sub_Subject_Type { get; set; }
    }
}
