//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty_of_University
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty_of_University()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Events = new HashSet<Event>();
        }
    
        public int id { get; set; }
        public int Faculty_id { get; set; }
        public int University_id { get; set; }
        public Nullable<System.DateTime> Cooperation_Start_Date { get; set; }
        public Nullable<int> Lv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual University University { get; set; }

		public static implicit operator Faculty_of_University(string v)
		{
			throw new NotImplementedException();
		}
	}
}
